
require "ifj21"

function abcdedgf(o: number)
end

function a(s: string, n: number)
end

function af(i: integer, s: string, n: number)
end

function abc(a: string, i: integer, s: string, n: number)
end

function abcd(kk: number) : string
end

function abcde(f: string, n: number) : integer, string
end

function abcdedg(i: integer, s: string, n: number) : number, integer
end

function abcdedgf(a: string, i: integer, s: string, n: number) : string, integer, number
end
