
require "ifj21"

function abc(a : integer, b : integer)
    local c : integer = 13 + 5

    if #"hello" then
        if 5 - 2 ~= 2 then
            if 6 + 5 == 11 then
                if 7 + 14 then
                else end
            else end
        else end
    else end

    if a + b > c then
            local d : string = "hello".."world"
        while a * (b + c) do
            local a : integer = 13 + 5 - 10 * 5 / 15
        end
    else end

    if nil then else end
end
